7-login-logout/myproject/blog/urls.py
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>', views.post_detail, name='post_detail'),
    path('sobre-nos/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

7-login-logout/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
]

7-login-logout/myproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

	POST_STATUS = (
		('active', 'Ativo'),
		('draft', 'Rascunho')
	)
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	body = models.TextField()
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)
	status = models.CharField(max_length=15, choices=POST_STATUS)

	def __str__(self):
	    return self.title

7-login-logout/myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post

def post_list(request):
	posts = Post.objects.all().order_by('-created_at')
	return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	return render(request, 'blog/post_detail.html', {'post':post})

def about(request):
	return render(request, 'blog/about_us.html')

def contact(request):
	return render(request, 'blog/contact.html')

7-login-logout/myproject/blog/templates/blog/about_us.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Sobre nós</h1>
		<p>Esta é a história do blog...</p>
	</div>
{% endblock %}

7-login-logout/myproject/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light">
	  <a class="navbar-brand" href="{% url 'blog:post_list' %}">Blog</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'blog:about' %}">Sobre nós</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'blog:contact' %}">Contato</a>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
						<a class="nav-link" href="{% url 'logout' %}">Sair</a>
				</li>
				{% else %}
				<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}">Login</a>
				</li>
				{% endif %}
	    </ul>
	  </div>
	</nav>
    <div class="row">
				{% if user.is_authenticated %}
					<p class="logged-in-p">
						Olá {{ user.username }} seja bem vindo, o que deseja fazer hoje? 
						<span class="sair"><a href="{% url 'logout' %}">Sair</a></span>
					</p>
				{% endif %}
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

7-login-logout/myproject/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Quer entrar em contato conosco?</h1>
	</div>
{% endblock %}

7-login-logout/myproject/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<div class="container">
		<h1>{{ post.title }}</h1>
		<p>Publicado em {{ post.created_at }} por {{ post.author }}</p>
		<p>{{ post.body|linebreaks }}</p>
	</div> 
{% endblock %}

7-login-logout/myproject/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}Listagem de Posts{% endblock %}

{% block content %}
	<div class="container">
		<div class="jumbotron jumbotron-fluid">
		  <div class="container">
		    <h1 class="display-4">Bem vindo ao Django blog!</h1>
		    <p class="lead">Aqui você vai encontrar os melhores posts sobre o framework.</p>
		  </div>
		</div>
		<div class="row">
				{% for post in posts %}
		    <div class="col">
		      <div class="card" style="width: 18rem;">
		        <img class="card-img-top" src="https://via.placeholder.com/286x180" alt="Card image cap">
		        <div class="card-body">
		          <h5 class="card-title">{{ post.title }}</h5>
							<p class="card-text">{{ post.body|truncatechars:50 }}...</p>
							<p>Criado em {{ post.created_at }} por {{ post.author }}</p>
		          <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Ver o post completo</a>
		        </div>
		      </div>
				</div>
				{% endfor %}
		</div>
	</div> 
{% endblock %}